import pptxgen from "pptxgenjs";
import { jsPDF } from "jspdf";

/**
 * Generates and triggers download of a real PowerPoint (.pptx) file using the new 4-color palette: #30364F, #ACBAC4, #E1D9BC, #F0F0DB
 */
export const exportToPptx = (title, rawContent, docId = "document") => {
  try {
    const pptx = new pptxgen();
    pptx.layout = "LAYOUT_16x9";
    pptx.author = "TransformAI Agentic Engine";

    // Define Dark Master Slide using Strict 4-Color Palette: #30364F, #ACBAC4, #E1D9BC, #F0F0DB
    pptx.defineSlideMaster({
      title: "TRANSFORMAI_SLATE",
      background: { color: "30364F" },
      objects: [
        { rect: { x: 0, y: 0, w: "100%", h: "0.15", fill: { color: "E1D9BC" } } },
        { text: { text: "TransformAI — Agentic Content Engine", options: { x: 0.5, y: 7.0, w: 5.0, h: 0.3, fontSize: 10, color: "ACBAC4" } } }
      ]
    });

    // 1. Cover Slide
    const cover = pptx.addSlide({ masterName: "TRANSFORMAI_SLATE" });
    cover.addText(title || "Presentation Deck", {
      x: 0.8, y: 2.2, w: "85%", h: 1.5,
      fontSize: 32, bold: true, color: "F0F0DB", fontFace: "Arial"
    });
    cover.addText("Generated by TransformAI Multi-Agent Engine", {
      x: 0.8, y: 3.8, w: "85%", h: 0.6,
      fontSize: 16, color: "E1D9BC", fontFace: "Arial"
    });

    // 2. Parse Slide Sections from Markdown
    const slideBlocks = rawContent.split(/####\s*/).filter(Boolean);

    slideBlocks.forEach((block, idx) => {
      const lines = block.split('\n').map(l => l.trim()).filter(Boolean);
      if (lines.length === 0) return;

      const rawHeading = lines[0].replace(/^Slide\s*\d+:\s*/i, '').replace(/###\s*/, '');
      const bullets = [];
      let speakerNotes = "";

      lines.slice(1).forEach(line => {
        if (line.toLowerCase().includes('speaker note:')) {
          speakerNotes += line.replace(/.*speaker note:\s*/i, '') + " ";
        } else if (line.startsWith('-') || line.startsWith('•') || line.startsWith('▪')) {
          const cleanLine = line.replace(/^[-•▪]\s*/, '').replace(/\*\*/g, '');
          if (cleanLine) bullets.push(cleanLine);
        }
      });

      const slide = pptx.addSlide({ masterName: "TRANSFORMAI_SLATE" });
      
      // Slide Title
      slide.addText(`Slide ${idx + 1}: ${rawHeading}`, {
        x: 0.8, y: 0.6, w: "88%", h: 0.8,
        fontSize: 22, bold: true, color: "E1D9BC", fontFace: "Arial"
      });

      // Bullets
      if (bullets.length > 0) {
        const bulletObjects = bullets.map(b => ({
          text: b,
          options: { bullet: true, fontSize: 15, color: "F0F0DB", lineSpacing: 26 }
        }));

        slide.addText(bulletObjects, {
          x: 0.8, y: 1.6, w: "88%", h: 4.8
        });
      }

      // Speaker Notes
      if (speakerNotes.trim()) {
        slide.addNotes(speakerNotes.trim());
      }
    });

    const filename = `${docId}_presentation.pptx`;
    pptx.writeFile({ fileName: filename });
    return filename;
  } catch (err) {
    console.error("PPTX Generation Error:", err);
    throw err;
  }
};

/**
 * Generates and triggers download of a formatted PDF document using 4-color palette
 */
export const exportToPdf = (title, rawContent, docId = "document") => {
  try {
    const doc = new jsPDF();
    doc.setFillColor(48, 54, 79); // #30364F
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(240, 240, 219); // #F0F0DB
    doc.setFontSize(18);
    doc.text(title, 14, 20);

    doc.setTextColor(225, 217, 188); // #E1D9BC
    doc.setFontSize(10);
    doc.text("TransformAI Generated Document", 14, 28);

    doc.setTextColor(240, 240, 219);
    doc.setFontSize(10);

    const splitText = doc.splitTextToSize(rawContent.replace(/[#*`]/g, ''), 180);
    let y = 38;
    splitText.forEach(line => {
      if (y > 280) {
        doc.addPage();
        doc.setFillColor(48, 54, 79);
        doc.rect(0, 0, 210, 297, "F");
        y = 20;
      }
      doc.text(line, 14, y);
      y += 6;
    });

    const filename = `${docId}_${title.toLowerCase().replace(/\s+/g, '_')}.pdf`;
    doc.save(filename);
    return filename;
  } catch (err) {
    console.error("PDF Export Error:", err);
    throw err;
  }
};
