import pptxgen from "pptxgenjs";
import { jsPDF } from "jspdf";

/**
 * Universal browser file download helper using Blob and temporary link trigger
 */
export const downloadBlob = (blob, filename) => {
  try {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.style.display = "none";
    document.body.appendChild(a);
    a.click();
    
    // Delay revocation by 60 seconds so browser has ample time to complete disk write
    setTimeout(() => {
      if (document.body.contains(a)) {
        document.body.removeChild(a);
      }
      URL.revokeObjectURL(url);
    }, 60000);
  } catch (err) {
    console.error("Browser download failed:", err);
  }
};

/**
 * Helper to sanitize strings to ASCII/printable text for jsPDF / PPTX standard font encoders
 */
const sanitizeText = (str) => {
  if (!str) return "";
  return str
    .replace(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F700}-\u{1F77F}\u{1F780}-\u{1F7FF}\u{1F800}-\u{1F8FF}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '')
    .replace(/[^\x00-\x7F]/g, ' ')
    .replace(/[#*`]/g, '');
};

/**
 * Generates and triggers download of a Markdown (.md) file
 */
export const exportToMarkdown = (title, rawContent, docId = "document") => {
  const cleanTitle = (title || "document").toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const filename = `${docId}_${cleanTitle}.md`;
  const header = `# ${title}\n*Generated by TransformAI Multi-Agent Engine*\n\n---\n\n`;
  const blob = new Blob([header + (rawContent || "")], { type: "text/markdown;charset=utf-8" });
  downloadBlob(blob, filename);
  return filename;
};

/**
 * Generates and triggers download of a Plain Text (.txt) file
 */
export const exportToText = (title, rawContent, docId = "document") => {
  const cleanTitle = (title || "document").toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const filename = `${docId}_${cleanTitle}.txt`;
  const textContent = `${(title || "DOCUMENT").toUpperCase()}\nGenerated by TransformAI Multi-Agent Engine\n${'='.repeat(50)}\n\n${(rawContent || "").replace(/[#*`]/g, '')}`;
  const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, filename);
  return filename;
};

/**
 * Generates and triggers download of a real PowerPoint (.pptx) file using 4-color palette
 */
export const exportToPptx = async (title, rawContent, docId = "document") => {
  try {
    const pptx = new pptxgen();
    pptx.layout = "LAYOUT_16x9";
    pptx.author = "TransformAI Agentic Engine";

    pptx.defineSlideMaster({
      title: "TRANSFORMAI_SLATE",
      background: { color: "000000" },
      objects: [
        { rect: { x: 0, y: 0, w: "100%", h: "0.15", fill: { color: "DFD0B8" } } },
        { text: { text: "TransformAI — Agentic Content Engine", options: { x: 0.5, y: 7.0, w: 5.0, h: 0.3, fontSize: 10, color: "DFD0B8" } } }
      ]
    });

    // 1. Cover Slide
    const cover = pptx.addSlide({ masterName: "TRANSFORMAI_SLATE" });
    cover.addText(sanitizeText(title || "Presentation Deck"), {
      x: 0.8, y: 2.2, w: "85%", h: 1.5,
      fontSize: 30, bold: true, color: "FFFFFF", fontFace: "Arial"
    });
    cover.addText("Generated by TransformAI Multi-Agent Engine", {
      x: 0.8, y: 3.8, w: "85%", h: 0.6,
      fontSize: 16, color: "E1DCC9", fontFace: "Arial"
    });

    // 2. Parse Slide Sections from Markdown
    const slideBlocks = (rawContent || "").split(/####\s*/).filter(Boolean);

    slideBlocks.forEach((block, idx) => {
      const lines = block.split('\n').map(l => l.trim()).filter(Boolean);
      if (lines.length === 0) return;

      const rawHeading = sanitizeText(lines[0].replace(/^Slide\s*\d+:\s*/i, '').replace(/###\s*/, ''));
      const bullets = [];
      let speakerNotes = "";

      lines.slice(1).forEach(line => {
        if (line.toLowerCase().includes('speaker note:')) {
          speakerNotes += sanitizeText(line.replace(/.*speaker note:\s*/i, '')) + " ";
        } else if (line.startsWith('-') || line.startsWith('•') || line.startsWith('▪')) {
          const cleanLine = sanitizeText(line.replace(/^[-•▪]\s*/, '').replace(/\*\*/g, ''));
          if (cleanLine) bullets.push(cleanLine);
        }
      });

      const slide = pptx.addSlide({ masterName: "TRANSFORMAI_SLATE" });

      slide.addText(`Slide ${idx + 1}: ${rawHeading}`, {
        x: 0.8, y: 0.6, w: "88%", h: 0.8,
        fontSize: 22, bold: true, color: "FFFFFF", fontFace: "Arial"
      });

      if (bullets.length > 0) {
        const bulletObjects = bullets.map(b => ({
          text: b,
          options: { bullet: true, fontSize: 14, color: "FFFFFF", lineSpacing: 24 }
        }));

        slide.addText(bulletObjects, {
          x: 0.8, y: 1.6, w: "88%", h: 4.8
        });
      }

      if (speakerNotes.trim()) {
        slide.addNotes(speakerNotes.trim());
      }
    });

    const cleanFilenameTitle = (title || "presentation").toLowerCase().replace(/[^a-z0-9]+/g, '_');
    const filename = `${docId}_${cleanFilenameTitle}.pptx`;
    
    // Generate Blob and download reliably
    const blob = await pptx.write({ outputType: "blob" });
    downloadBlob(blob, filename);
    return filename;
  } catch (err) {
    console.error("PPTX Export Error:", err);
    // Fallback: Export text if PowerPoint generation fails
    return exportToText(title, rawContent, docId);
  }
};

/**
 * Generates and triggers download of a formatted PDF document using Black & Warm Sand Gold palette
 */
export const exportToPdf = (title, rawContent, docId = "document") => {
  try {
    const doc = new jsPDF();
    const cleanDocTitle = sanitizeText(title || "Generated Report");

    doc.setFillColor(0, 0, 0); // #000000
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(255, 255, 255); // #FFFFFF
    doc.setFontSize(16);
    doc.text(cleanDocTitle, 14, 20);

    doc.setTextColor(223, 208, 184); // #DFD0B8
    doc.setFontSize(9);
    doc.text("TransformAI Generated Report", 14, 27);

    doc.setDrawColor(225, 220, 201); // #E1DCC9
    doc.line(14, 31, 196, 31);

    doc.setTextColor(255, 255, 255); // #FFFFFF
    doc.setFontSize(9.5);

    const sanitizedBody = sanitizeText(rawContent);
    const splitText = doc.splitTextToSize(sanitizedBody, 180);
    let y = 38;

    splitText.forEach(line => {
      if (y > 280) {
        doc.addPage();
        doc.setFillColor(0, 0, 0); // #000000
        doc.rect(0, 0, 210, 297, "F");
        y = 20;
      }
      doc.text(line, 14, y);
      y += 5.5;
    });

    const cleanFilenameTitle = (title || "report").toLowerCase().replace(/[^a-z0-9]+/g, '_');
    const filename = `${docId}_${cleanFilenameTitle}.pdf`;
    
    // Output Blob and trigger browser download
    const pdfBlob = doc.output("blob");
    downloadBlob(pdfBlob, filename);
    return filename;
  } catch (err) {
    console.error("PDF Export Error:", err);
    // Fallback: Export text if PDF generation encounters error
    return exportToText(title, rawContent, docId);
  }
};
