import pptxgen from "pptxgenjs";
import { jsPDF } from "jspdf";
import { generateCybersecurityAdvisoryPdf } from "./advisoryPdfGenerator.js";
import { extractCoreContentIntelligence } from "../services/coreIntelligence.js";
import { generatePresentationPptx } from "./presentationPptxGenerator.js";
import { buildStructuredPresentation } from "../services/presentationModel.js";
import { generateInfographicPdfBlob, exportInfographicAsPng, exportInfographicAsJpg } from "./infographicGenerator.js";
import { buildStructuredInfographic } from "../services/infographicModel.js";

/**
 * Universal browser file download helper using Blob and temporary link trigger
 */
export const downloadBlob = (blob, filename) => {
  try {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 150);
  } catch (err) {
    console.error("Browser download failed:", err);
  }
};

/**
 * Generates and triggers download of a Markdown (.md) file
 */
export const exportToMarkdown = (title, rawContent, docId = "document") => {
  const cleanTitle = (title || "document").toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const filename = `${docId}_${cleanTitle}.md`;
  const header = `# ${title}\n*Generated by SyntaxX Agentic Intelligence Engine*\n\n---\n\n`;
  const blob = new Blob([header + (rawContent || "")], { type: "text/markdown;charset=utf-8" });
  downloadBlob(blob, filename);
  return filename;
};

/**
 * Generates and triggers download of a Plain Text (.txt) file
 */
export const exportToText = (title, rawContent, docId = "document") => {
  const cleanTitle = (title || "document").toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const filename = `${docId}_${cleanTitle}.txt`;
  const textContent = `${(title || "DOCUMENT").toUpperCase()}\nGenerated by SyntaxX Agentic Intelligence Engine\n${'='.repeat(50)}\n\n${(rawContent || "").replace(/[#*`]/g, '')}`;
  const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, filename);
  return filename;
};

/**
 * Generates and triggers download of a publication-grade PowerPoint (.pptx) presentation
 * Uses native slide shapes, tables, cards, arrow flows, headers/footers, and embedded speaker notes.
 */
export const exportToPptx = async (title, rawContent, docId = "document", presentationData = null) => {
  try {
    // 1. If explicit structured presentation data is provided, generate directly
    if (presentationData && (presentationData.slides || presentationData.presentation?.slides)) {
      return await generatePresentationPptx(presentationData);
    }

    // 2. If rawContent is JSON string containing structured presentation, parse and generate
    if (typeof rawContent === 'string' && rawContent.trim().startsWith('{')) {
      try {
        const parsed = JSON.parse(rawContent);
        if (parsed?.presentation?.slides || parsed?.slides) {
          return await generatePresentationPptx(parsed);
        }
      } catch (e) {
        // fall through to model generator
      }
    }

    // 3. Extract core intelligence and build structured presentation model
    const coreIntel = extractCoreContentIntelligence({ id: docId, title }, { content: rawContent });
    const structuredPres = buildStructuredPresentation(coreIntel);
    return await generatePresentationPptx(structuredPres);
  } catch (err) {
    console.error("PPTX Generation Error:", err);
    throw err;
  }
};

/**
 * Generates and triggers download of a formatted PDF document using SyntaxX 4-color palette
 */
export const exportToPdf = (title, rawContent, docId = "document") => {
  try {
    const doc = new jsPDF();
    doc.setFillColor(0, 0, 0); // #000000 Black
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(225, 220, 201); // #E1DCC9 Cream
    doc.setFontSize(18);
    doc.text(title || "Generated Report", 14, 20);

    doc.setTextColor(184, 178, 160); // Muted cream
    doc.setFontSize(10);
    doc.text("SyntaxX Agentic Intelligence Suite", 14, 28);

    doc.setTextColor(225, 220, 201);
    doc.setFontSize(10);

    const splitText = doc.splitTextToSize((rawContent || "").replace(/[#*`]/g, ''), 180);
    let y = 38;
    splitText.forEach(line => {
      if (y > 280) {
        doc.addPage();
        doc.setFillColor(0, 0, 0);
        doc.rect(0, 0, 210, 297, "F");
        y = 20;
      }
      doc.text(line, 14, y);
      y += 6;
    });

    const cleanTitle = (title || "report").toLowerCase().replace(/[^a-z0-9]+/g, '_');
    const filename = `${docId}_${cleanTitle}.pdf`;
    doc.save(filename);
    return filename;
  } catch (err) {
    console.error("PDF Export Error:", err);
    throw err;
  }
};

// Cache keyed by `${sourceId}:${outputType}` to prevent stale cross-source reuse
const pdfBlobCache = new Map();

/**
 * Universal PDF generation pipeline:
 * Fetches publication-grade ReportLab Platypus PDF from backend engine or generates fallback client-side PDF.
 * Returns { blob, arrayBuffer, filename, title, advisoryId, isBackendGenerated }
 * Enables in-app PDF preview and guaranteed identical download.
 */
export const fetchOrGeneratePdfBlob = async (formatId, selectedDoc, result) => {
  try {
    const intel = extractCoreContentIntelligence(selectedDoc, result);
    const sourceId = selectedDoc?.id || intel?.metadata?.advisoryId || 'document';
    const cacheKey = `${sourceId}:${formatId}`;

    if (pdfBlobCache.has(cacheKey)) {
      return pdfBlobCache.get(cacheKey);
    }

    const advisoryId = intel?.metadata?.advisoryId || (sourceId === 'cybersecurity' ? 'CSIRT-2024-38077-ADV' : (sourceId === 'health_advisory' ? 'MOH-PHE-2026-04' : (sourceId === 'research_paper' ? 'RESEARCH-LLM-2026' : 'TAI-ADV-2026-88421')));
    let endpoint = '';
    let filename = '';
    let title = '';

    if (formatId === 'advisory_doc') {
      endpoint = 'http://127.0.0.1:8000/api/export/advisory-pdf';
      filename = `${advisoryId}_Security_Advisory.pdf`;
      title = 'Structured Advisory';
    } else if (formatId === 'exec_summary') {
      endpoint = 'http://127.0.0.1:8000/api/export/executive-pdf';
      filename = `${advisoryId}_Executive_Summary.pdf`;
      title = 'Executive Summary';
    } else if (formatId === 'infographic_pkg') {
      endpoint = 'http://127.0.0.1:8000/api/export/infographic-pdf';
      filename = `${advisoryId}_Visual_Infographic.pdf`;
      title = 'Infographic Content & Layout';
    } else {
      endpoint = 'http://127.0.0.1:8000/api/export/advisory-pdf';
      filename = `${advisoryId}_Document.pdf`;
      title = 'Document PDF';
    }

    // 1. Primary: Stream publication-grade PDF from Python ReportLab Platypus backend
    try {
      const model = result?.structuredInfographic || buildStructuredInfographic(result?.content, result, selectedDoc);
      console.log("INFOGRAPHIC PDF DATA", model);
      const payload = {
        ...(intel || {}),
        structuredInfographic: model,
        title: model?.title || intel?.metadata?.advisoryTitle || selectedDoc?.title,
        subtitle: model?.subtitle || intel?.metadata?.subtitle,
        advisory_id: advisoryId,
        cve: model?.cve || model?.identifier || intel?.vulnerability?.cve || intel?.threat_at_a_glance?.cve,
        summary: model?.summary || intel?.executive_summary,
        findings: model?.findings || model?.keyFindings || intel?.key_findings,
        key_findings: model?.findings || model?.keyFindings || intel?.key_findings,
        attack_chain: model?.attack_chain || model?.attackFlow || intel?.attack_chain,
        metrics: model?.metrics,
      };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (response.ok) {
        const rawBlob = await response.blob();
        const pdfBlob = new Blob([rawBlob], { type: 'application/pdf' });
        const pdfUrl = URL.createObjectURL(pdfBlob);
        const arrayBuffer = await pdfBlob.arrayBuffer();
        const output = {
          blob: pdfBlob,
          url: pdfUrl,
          arrayBuffer,
          filename,
          title,
          advisoryId,
          sourceId,
          isBackendGenerated: true,
        };
        pdfBlobCache.set(cacheKey, output);
        return output;
      }
      console.warn(`Backend ${formatId} PDF generation returned status:`, response.status);
    } catch (fetchErr) {
      console.warn(`ReportLab backend unreachable for ${formatId}, activating client-side fallback generator:`, fetchErr);
    }

    // 2. Secondary: Client-side fallback generation matching SyntaxX 4-color palette
    let fallbackBlob;
    if (formatId === 'advisory_doc') {
      const res = generateCybersecurityAdvisoryPdf(intel, true);
      fallbackBlob = new Blob([res.blob], { type: 'application/pdf' });
    } else if (formatId === 'infographic_pkg') {
      const model = result?.structuredInfographic || buildStructuredInfographic(result?.content, result, selectedDoc);
      fallbackBlob = await generateInfographicPdfBlob(model);
    } else {
      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });
      // Pure black canvas
      doc.setFillColor(0, 0, 0);
      doc.rect(0, 0, 210, 297, "F");

      // Dark brown header block
      doc.setFillColor(31, 21, 12);
      doc.rect(12, 14, 186, 26, "F");
      doc.setDrawColor(65, 45, 21);
      doc.setLineWidth(0.5);
      doc.rect(12, 14, 186, 26, "D");

      doc.setTextColor(225, 220, 201);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(title.toUpperCase(), 18, 24);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(184, 178, 160);
      doc.text(`SYNTAXX AGENTIC INTELLIGENCE SUITE • ${advisoryId}`, 18, 32);

      // Deep brown card
      doc.setFillColor(31, 21, 12);
      doc.rect(12, 45, 186, 230, "F");
      doc.setDrawColor(65, 45, 21);
      doc.rect(12, 45, 186, 230, "D");

      doc.setTextColor(225, 220, 201);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(intel?.metadata?.advisoryTitle || "Executive Briefing & Intelligence Synthesis", 18, 56);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(225, 220, 201);
      const raw = result?.content || "";
      const bodyLines = doc.splitTextToSize(raw.replace(/[#*`]/g, ''), 174);
      doc.text(bodyLines.slice(0, 48), 18, 66);

      fallbackBlob = new Blob([doc.output('blob')], { type: 'application/pdf' });
    }

    const arrayBuffer = await fallbackBlob.arrayBuffer();
    const pdfUrl = URL.createObjectURL(fallbackBlob);
    const fallbackOutput = {
      blob: fallbackBlob,
      url: pdfUrl,
      arrayBuffer,
      filename,
      title,
      advisoryId,
      sourceId,
      isBackendGenerated: false,
    };
    pdfBlobCache.set(cacheKey, fallbackOutput);
    return fallbackOutput;
  } catch (err) {
    console.error(`Error generating PDF blob for ${formatId}:`, err);
    throw err;
  }
};

/**
 * Invalidate all cached PDF blobs across sources
 */
export const clearPdfBlobCache = () => {
  try {
    if (typeof pdfBlobCache !== 'undefined' && pdfBlobCache) {
      pdfBlobCache.forEach((item) => {
        if (item?.url) {
          try { URL.revokeObjectURL(item.url); } catch (e) {}
        }
      });
      pdfBlobCache.clear();
    }
  } catch (err) {
    console.warn("Notice clearing PDF blob cache:", err);
  }
};

/**
 * Generates an official, publication-grade cybersecurity advisory PDF from Core Content Intelligence
 * Streams publication-grade Platypus PDF from backend engine with zero-overlapping layout.
 */
export const exportStructuredAdvisoryPdf = async (selectedDoc, result) => {
  try {
    const { blob, filename } = await fetchOrGeneratePdfBlob('advisory_doc', selectedDoc, result);
    downloadBlob(blob, filename);
    return filename;
  } catch (err) {
    console.error("Structured Advisory PDF Generation Error:", err);
    throw err;
  }
};

/**
 * Generates an official, publication-grade executive summary briefing PDF from Core Content Intelligence
 * Streams publication-grade Platypus PDF from backend engine with zero-overlapping layout across all 13 sections.
 */
export const exportExecutiveSummaryPdf = async (selectedDoc, result) => {
  try {
    const { blob, filename } = await fetchOrGeneratePdfBlob('exec_summary', selectedDoc, result);
    downloadBlob(blob, filename);
    return filename;
  } catch (err) {
    console.error("Executive Summary PDF Generation Error:", err);
    throw err;
  }
};

/**
 * Generates an official, publication-grade visual infographic PDF from Core Content Intelligence
 */
export const exportInfographicPdf = async (selectedDoc, result) => {
  try {
    const { blob, filename } = await fetchOrGeneratePdfBlob('infographic_pkg', selectedDoc, result);
    downloadBlob(blob, filename);
    return filename;
  } catch (err) {
    console.error("Infographic PDF Generation Error:", err);
    throw err;
  }
};

/**
 * Generates and triggers download of high-resolution Infographic Image (PNG or JPG)
 * Uses the exact same 1080x1920 layout engine as the PDF.
 */
export const exportInfographicImage = async (selectedDoc, result, format = 'png') => {
  try {
    const model = result?.structuredInfographic || buildStructuredInfographic(result?.content, result, selectedDoc);
    const intel = extractCoreContentIntelligence(selectedDoc, result);
    const sourceId = selectedDoc?.id || intel?.metadata?.advisoryId || 'document';
    const advisoryId = intel?.metadata?.advisoryId || (sourceId === 'cybersecurity' ? 'CSIRT-2024-38077-ADV' : (sourceId === 'health_advisory' ? 'MOH-PHE-2026-04' : (sourceId === 'research_paper' ? 'RESEARCH-LLM-2026' : 'TAI-ADV-2026-88421')));
    const ext = format.toLowerCase() === 'jpg' ? 'jpg' : 'png';
    const filename = `${advisoryId}_Visual_Infographic.${ext}`;
    
    if (ext === 'jpg') {
      await exportInfographicAsJpg(model, filename);
    } else {
      await exportInfographicAsPng(model, filename);
    }
    return filename;
  } catch (err) {
    console.error(`Infographic ${format.toUpperCase()} Generation Error:`, err);
    throw err;
  }
};

/**
 * Generates an official, publication-grade video production package PDF from Core Content Intelligence
 * Streams publication-grade Platypus PDF from backend engine covering all 14 broadcast production sections.
 */
export const exportVideoPackagePdf = async (selectedDoc, result) => {
  try {
    const intel = extractCoreContentIntelligence(selectedDoc, result);
    const advisoryId = intel?.metadata?.advisoryId || 'TAI-ADV-2026-88421';
    const filename = `${advisoryId}_Video_Production_Package.pdf`;

    // Attempt to stream publication-grade PDF from Python ReportLab Platypus engine
    try {
      const response = await fetch('http://127.0.0.1:8000/api/export/video-pdf', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(intel),
      });

      if (response.ok) {
        const blob = await response.blob();
        downloadBlob(blob, filename);
        return filename;
      }
      console.warn("Backend Video PDF generation returned status:", response.status);
    } catch (fetchErr) {
      console.warn("ReportLab backend connection failed for video package:", fetchErr);
    }

    // Client-side fallback if backend server is unreachable
    const doc = new jsPDF();
    doc.setFillColor(11, 25, 48);
    doc.rect(0, 0, 210, 297, "F");
    doc.setTextColor(240, 240, 219);
    doc.setFontSize(16);
    doc.text("VIDEO SCRIPT PRODUCTION PACKAGE", 14, 22);
    doc.setFontSize(10);
    doc.setTextColor(225, 217, 188);
    doc.text(intel?.metadata?.advisoryTitle || "Video Production Package", 14, 30);
    const bodyLines = doc.splitTextToSize((result?.content || "").replace(/[#*`]/g, ''), 180);
    doc.text(bodyLines, 14, 42);
    doc.save(filename);
    return filename;
  } catch (err) {
    console.error("Video Package PDF Generation Error:", err);
    throw err;
  }
};


